name: build-connector
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install
      run: ./abconw install
    - name: Check
      run: ./abconw check
    - name: Test
      run: ./abconw test
    - name: SAT
      run: ./abconw sat

